package main

import "dqq/go/basic/d_concurrence"

func main() {
	// d_concurrence.SimpleGoroutine()
	// d_concurrence.SubRoutine()
	// d_concurrence.WaitGroup()
	// d_concurrence.Atomic()
	// d_concurrence.Lock()
	// d_concurrence.ReentranceRLock(3)
	// d_concurrence.ReentranceWLock(3)
	// d_concurrence.RLockExclusion()
	// d_concurrence.WLockExclusion()
	// d_concurrence.CollectionSafety()
	// d_concurrence.ServiceMain()
	// d_concurrence.CloseChannel()
	// d_concurrence.ChannelBlock()
	// d_concurrence.TraverseChannel()
	// d_concurrence.Block()
	// d_concurrence.Broadcast()
	// d_concurrence.CutDownLatch()
	// d_concurrence.CondSignal()
	// d_concurrence.ChannelSignal()
	// d_concurrence.CondBroadcast()
	// d_concurrence.ChannelBroadcast()
	// d_concurrence.DealMassFile("z_data/biz_log")
	// d_concurrence.QpsLimit()
	// d_concurrence.RoutineLimit()
	// d_concurrence.ListenMultiWay()
	// d_concurrence.SelectBlock()
	// d_concurrence.Timeout1()
	// d_concurrence.Timeout2()
	// d_concurrence.InheritTimeout()
	d_concurrence.RoutineID()
	// d_concurrence.ContextWithValue()
}
